<template><section class="surface-card interaction-card"><div class="action-row"><button class="pill-button" :class="{'is-active':state.favorite}" @click="toggle('favorite')">{{state.favorite?'已收藏':'收藏'}}</button><button class="pill-button" :class="{'is-active':state.watchlist}" @click="toggle('watchlist')">{{state.watchlist?'已想看':'想看'}}</button><button class="pill-button" :class="{'is-active':state.watched}" @click="toggle('watched')">{{state.watched?'已看过':'看过'}}</button><div class="rating"><span>我的评分</span><el-rate v-model="rating" :max="10" @change="saveRating"/></div></div><div class="comment-compose"><el-input v-model="content" maxlength="500" show-word-limit type="textarea" :rows="3" placeholder="写下你对这部影片的看法"/><button class="pill-button is-active" @click="submit">发表评论</button></div><div class="comments"><h3>用户评论</h3><div v-for="item in comments" :key="item.id" class="comment"><div><b>{{item.nickname}}</b><small>{{format(item.createTime)}}</small></div><p>{{item.content}}</p><el-button v-if="item.userId===store.profile?.id" link type="danger" @click="remove(item)">删除</el-button></div><el-empty v-if="!comments.length" description="还没有评论"/></div></section></template>
<script setup>
import{onMounted,ref,watch}from'vue';import{ElMessage}from'element-plus';import{useRouter}from'vue-router';import{useUserStore}from'@/stores/user';import{getInteraction,recordView,setFavorite,setWatchlist,setWatched,setRating,getComments,addComment,deleteOwnComment}from'@/api/interaction'
const props=defineProps({movieId:{type:Number,required:true}}),store=useUserStore(),router=useRouter(),state=ref({favorite:false,watchlist:false,watched:false}),rating=ref(0),content=ref(''),comments=ref([])
const login=()=>{if(store.token)return true;router.push({path:'/login',query:{redirect:router.currentRoute.value.fullPath}});return false}
async function load(){const c=await getComments(props.movieId);comments.value=c.data?.records||[];if(store.token){const r=await getInteraction(props.movieId);state.value=r.data||{};rating.value=Number(state.value.rating||0);await recordView(props.movieId)}}
async function toggle(k){if(!login())return;const on=!state.value[k];if(k==='favorite')await setFavorite(props.movieId,on);if(k==='watchlist')await setWatchlist(props.movieId,on);if(k==='watched')await setWatched(props.movieId,on);state.value[k]=on;if(k==='watched'&&on)state.value.watchlist=false;ElMessage.success(on?(k==='watched'?'已标记为看过':'操作成功'):'已取消')}
async function saveRating(v){if(!login())return;await setRating(props.movieId,v);ElMessage.success('评分已保存')}
async function submit(){if(!login()||!content.value.trim())return;await addComment(props.movieId,content.value);content.value='';await load();ElMessage.success('评论已发布')}
async function remove(i){await deleteOwnComment(i.id);await load()}
const format=v=>v?new Date(v).toLocaleString('zh-CN'):'';watch(()=>props.movieId,load);onMounted(load)
</script><style scoped>.interaction-card{padding:24px}.action-row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.rating{display:flex;align-items:center;gap:10px;margin-left:auto}.comment-compose{display:grid;gap:12px;margin-top:22px}.comment-compose button{justify-self:end}.comments{margin-top:24px}.comment{position:relative;padding:16px 0;border-top:1px solid var(--border-soft)}.comment div{display:flex;gap:10px;align-items:center}.comment small{color:var(--text-muted)}.comment p{margin:8px 70px 0 0;color:var(--text-secondary)}.comment .el-button{position:absolute;right:0;top:12px}</style>