<template><section class="space-y-6 pt-20"><div class="surface-card p-6"><p class="section-kicker">Movie Library</p><h1 class="mt-3 text-3xl font-semibold md:text-5xl">影视库</h1><div class="filters"><div class="filter-row"><el-input v-model="query.keyword" clearable placeholder="搜索影片标题" class="filter-input" @keyup.enter="search"/><button class="pill-button is-active" @click="search">查询</button><button class="pill-button" @click="reset">重置</button></div><div class="filter-row"><span class="filter-label">类型</span><div class="pill-group"><button v-for="v in options.categories" :key="v" class="pill-button" :class="pillClass('categories','excludeCategories',v)" @click="toggleFilter('categories','excludeCategories',v)" @contextmenu.prevent="toggleExclude('categories','excludeCategories',v)">{{ v }}</button></div></div><div class="filter-row"><span class="filter-label">地区</span><div class="pill-group"><button v-for="v in options.regions" :key="v" class="pill-button" :class="pillClass('regions','excludeRegions',v)" @click="toggleFilter('regions','excludeRegions',v)" @contextmenu.prevent="toggleExclude('regions','excludeRegions',v)">{{ v }}</button></div></div><div class="filter-row"><span class="filter-label">年份</span><div class="pill-group"><button v-for="v in options.years" :key="v" class="pill-button" :class="pillClass('years','excludeYears',v)" @click="toggleFilter('years','excludeYears',v)" @contextmenu.prevent="toggleExclude('years','excludeYears',v)">{{ v }}</button></div></div><div class="sort-row"><el-dropdown trigger="click" @command="onSortChange"><span class="sort-trigger">排序：{{ sortLabel }} <span class="sort-arrow">▾</span></span><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="item in sortOptions" :key="item.value" :command="item.value">{{ item.label }}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></div></div><div v-loading="loading"><MovieList :movies="movies"/><el-empty v-if="!loading&&!movies.length" description="没有符合条件的影片"/></div><div class="pager"><el-pagination v-model:current-page="query.pageNum" :page-size="query.pageSize" :total="total" layout="prev, pager, next, jumper, total" @current-change="goPage"/></div></section></template>
<script setup>
import{onMounted,reactive,ref,computed}from'vue';import{getMoviePage,getMovieFilters}from'@/api/movie';import MovieList from'@/components/MovieList.vue'
const movies=ref([]),total=ref(0),loading=ref(false),options=reactive({categories:[],regions:[],years:[]}),query=reactive({keyword:'',categories:[],excludeCategories:[],regions:[],excludeRegions:[],years:[],excludeYears:[],sort:'hot',pageNum:1,pageSize:20})
const sortOptions=[{value:'hot',label:'热门优先'},{value:'rating-desc',label:'评分从高到低'},{value:'rating-asc',label:'评分从低到高'},{value:'favorite-desc',label:'收藏最多'},{value:'release-desc',label:'上映时间从新到旧'},{value:'release-asc',label:'上映时间从旧到新'}]
const sortLabel=computed(()=>sortOptions.find(o=>o.value===query.sort)?.label||'热门优先')
function onSortChange(v){query.sort=v;query.pageNum=1;load();window.scrollTo({top:0,behavior:'smooth'})}
function pillClass(incKey,excKey,val){return{'is-active':query[incKey].includes(val),'is-excluded':query[excKey].includes(val)}}
function toggleFilter(incKey,excKey,val){const inc=query[incKey],exc=query[excKey],i=exc.indexOf(val);if(i!==-1){exc.splice(i,1);inc.push(val)}else{const j=inc.indexOf(val);j===-1?inc.push(val):inc.splice(j,1)}query.pageNum=1;load();window.scrollTo({top:0,behavior:'smooth'})}
function toggleExclude(incKey,excKey,val){const inc=query[incKey],exc=query[excKey],j=inc.indexOf(val);if(j!==-1){inc.splice(j,1);exc.push(val)}else{const i=exc.indexOf(val);i===-1?exc.push(val):exc.splice(i,1)}query.pageNum=1;load();window.scrollTo({top:0,behavior:'smooth'})}
async function load(){const params={keyword:query.keyword||undefined,sort:query.sort,pageNum:query.pageNum,pageSize:query.pageSize};if(query.categories.length)params.categories=query.categories;if(query.excludeCategories.length)params.excludeCategories=query.excludeCategories;if(query.regions.length)params.regions=query.regions;if(query.excludeRegions.length)params.excludeRegions=query.excludeRegions;if(query.years.length)params.years=query.years;if(query.excludeYears.length)params.excludeYears=query.excludeYears;loading.value=true;try{const r=await getMoviePage(params);movies.value=r.data?.records||[];total.value=Number(r.data?.total||0)}finally{loading.value=false}}
function goPage(p){query.pageNum=p;load();window.scrollTo({top:0,behavior:'smooth'})}
function search(){query.pageNum=1;load();window.scrollTo({top:0,behavior:'smooth'})}function reset(){query.categories=[];query.excludeCategories=[];query.regions=[];query.excludeRegions=[];query.years=[];query.excludeYears=[];query.keyword='';query.sort='hot';query.pageNum=1;load();window.scrollTo({top:0,behavior:'smooth'})}
onMounted(async()=>{const r=await getMovieFilters();Object.assign(options,r.data||{});await load()})
</script><style scoped>.filters{margin-top:24px;display:flex;flex-direction:column;gap:16px}.filter-row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.filter-input{flex:1;min-width:200px;max-width:360px}.filter-label{font-size:0.82rem;font-weight:650;color:var(--text-secondary);white-space:nowrap;min-width:36px}.pill-group{display:flex;flex-wrap:wrap;gap:8px}.pill-button.is-excluded{background:rgba(220,38,38,0.12);color:var(--text-secondary);text-decoration:line-through;border-color:rgba(220,38,38,0.3)}html[data-theme='dark'] .pill-button.is-excluded{background:rgba(248,113,113,0.12);border-color:rgba(248,113,113,0.25)}.sort-row{display:flex;justify-content:flex-end;margin-top:4px}.sort-trigger{font-size:0.85rem;color:var(--text-secondary);cursor:pointer;padding:6px 0;transition:color 0.2s ease;user-select:none}.sort-trigger:hover{color:var(--text-primary)}.sort-arrow{font-size:0.7rem;margin-left:2px;opacity:0.6}.pager{display:flex;justify-content:center;margin-top:24px}@media(max-width:600px){.filter-row{flex-direction:column;align-items:flex-start}.filter-input{max-width:100%;width:100%}}</style>
