<template><section class="space-y-6 pt-20"><div class="surface-card p-6"><p class="section-kicker">My Movie Mind</p><h1>个人中心</h1><p>管理资料，以及你的收藏、评分、想看和看过记录。</p></div><div class="surface-card p-6"><el-tabs v-model="tab" @tab-change="load"><el-tab-pane label="个人资料" name="profile"><el-form label-position="top" class="profile-form"><el-form-item label="用户名"><el-input :model-value="form.username" disabled/></el-form-item><el-form-item label="昵称"><el-input v-model="form.nickname"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item></el-form><button class="pill-button is-active" @click="saveProfile">保存资料</button><el-divider/><h3>修改密码</h3><el-form label-position="top" class="profile-form"><el-form-item label="原密码"><el-input v-model="password.oldPassword" type="password" show-password/></el-form-item><el-form-item label="新密码"><el-input v-model="password.newPassword" type="password" show-password/></el-form-item><el-form-item label="确认新密码"><el-input v-model="password.confirmPassword" type="password" show-password/></el-form-item></el-form><button class="pill-button" @click="changePassword">修改密码</button></el-tab-pane><el-tab-pane v-for="item in tabs" :key="item.name" :label="item.label" :name="item.name"><div class="record-grid"><RouterLink v-for="r in records" :key="r.id" :to="`/movies/${r.movieId}`" class="record-card"><img v-if="r.posterUrl" :src="r.posterUrl"/><div><b>{{r.title}}</b><p v-if="r.score">我的评分：{{r.score}}</p><small>{{format(r.actionTime)}}</small></div></RouterLink></div><el-empty v-if="!records.length" :description="'还没有'+item.label+'记录'"/></el-tab-pane></el-tabs></div></section></template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{useRouter}from'vue-router';import{getProfile,updateProfile,changePassword as updatePassword}from'@/api/user';import{getMyRecords}from'@/api/interaction';import{useUserStore}from'@/stores/user'
const store=useUserStore(),router=useRouter(),tab=ref('profile'),records=ref([]),form=reactive({username:'',nickname:'',email:''}),password=reactive({oldPassword:'',newPassword:'',confirmPassword:''}),tabs=[{name:'favorites',label:'收藏'},{name:'ratings',label:'评分'},{name:'watchlist',label:'想看'},{name:'watched',label:'看过'},{name:'views',label:'浏览'}]
async function init(){const r=await getProfile();Object.assign(form,r.data);store.setProfile({...store.profile,...r.data})}
async function load(name){if(!name||name==='profile')return;const r=await getMyRecords(name,{pageSize:50});records.value=r.data?.records||[]}
async function saveProfile(){const r=await updateProfile(form);store.setProfile({...store.profile,...r.data});ElMessage.success('资料已保存')}
async function changePassword(){await updatePassword(password);store.logout();ElMessage.success('密码已修改，请重新登录');router.push('/login')}
const format=v=>v?new Date(v).toLocaleString('zh-CN'):'';onMounted(init)
</script><style scoped>.profile-form{max-width:520px}.record-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px}.record-card{display:flex;gap:14px;padding:12px;border:1px solid var(--border-soft);border-radius:16px;color:var(--text-primary);text-decoration:none}.record-card img{width:58px;height:82px;border-radius:8px;object-fit:cover}.record-card p,.record-card small{color:var(--text-muted)}</style>