package com.example.movie.controller;
import com.example.movie.common.*;import com.example.movie.service.InteractionService;import lombok.RequiredArgsConstructor;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.util.Map;
@RestController @RequiredArgsConstructor public class InteractionController{private final InteractionService s;
@GetMapping("/api/movies/{id}/interaction")public Result<Map<String,Object>>state(Authentication a,@PathVariable Long id){return Result.success(s.state(a.getName(),id));}
@PostMapping("/api/movies/{id}/view")public Result<Void>view(Authentication a,@PathVariable Long id){s.view(a.getName(),id);return Result.success(null);}
@PostMapping("/api/favorites/{id}")public Result<Void>fav(Authentication a,@PathVariable Long id){s.favorite(a.getName(),id,true);return Result.success(null);}@DeleteMapping("/api/favorites/{id}")public Result<Void>unfav(Authentication a,@PathVariable Long id){s.favorite(a.getName(),id,false);return Result.success(null);}
@PostMapping("/api/ratings")public Result<Void>rate(Authentication a,@RequestBody Map<String,Object>b){s.rate(a.getName(),Long.valueOf(b.get("movieId").toString()),new BigDecimal(b.get("score").toString()));return Result.success(null);}
@PostMapping("/api/watchlist/{id}")public Result<Void>want(Authentication a,@PathVariable Long id){s.want(a.getName(),id,true);return Result.success(null);}@DeleteMapping("/api/watchlist/{id}")public Result<Void>unwant(Authentication a,@PathVariable Long id){s.want(a.getName(),id,false);return Result.success(null);}
@PostMapping("/api/watch-history/{id}")public Result<Void>watched(Authentication a,@PathVariable Long id){s.watched(a.getName(),id,true);return Result.success(null);}@DeleteMapping("/api/watch-history/{id}")public Result<Void>unwatched(Authentication a,@PathVariable Long id){s.watched(a.getName(),id,false);return Result.success(null);}
@PostMapping("/api/comments")public Result<Long>comment(Authentication a,@RequestBody Map<String,Object>b){return Result.success(s.comment(a.getName(),Long.valueOf(b.get("movieId").toString()),String.valueOf(b.get("content"))));}@DeleteMapping("/api/comments/{id}")public Result<Void>del(Authentication a,@PathVariable Long id){s.deleteComment(a.getName(),id);return Result.success(null);}
@GetMapping("/api/movies/{id}/comments")public Result<PageResult<Map<String,Object>>>comments(@PathVariable Long id,@RequestParam(defaultValue="1")long pageNum,@RequestParam(defaultValue="10")long pageSize){return Result.success(s.comments(id,pageNum,pageSize));}
@GetMapping("/api/user/records/{type}")public Result<PageResult<Map<String,Object>>>mine(Authentication a,@PathVariable String type,@RequestParam(defaultValue="1")long pageNum,@RequestParam(defaultValue="12")long pageSize){return Result.success(s.mine(a.getName(),type,pageNum,pageSize));}
}