package com.example.movie.service;
import com.example.movie.common.PageResult;import lombok.RequiredArgsConstructor;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;
@Service @RequiredArgsConstructor public class InteractionService{
 private final JdbcTemplate db; private Long uid(String u){return db.queryForObject("SELECT id FROM user WHERE username=? AND status=1 AND deleted=0",Long.class,u);}
 private void movie(Long id){if(Boolean.FALSE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM movie WHERE id=? AND deleted=0 AND status=1)",Boolean.class,id)))throw new IllegalArgumentException("影片不存在或已下架");}
 private boolean has(String t,Long u,Long m){return Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM "+t+" WHERE user_id=? AND movie_id=?)",Boolean.class,u,m));}
 public Map<String,Object> state(String n,Long m){Long u=uid(n);Map<String,Object>r=new LinkedHashMap<>();r.put("favorite",has("favorite",u,m));r.put("watchlist",has("watchlist",u,m));r.put("watched",has("watch_history",u,m));List<BigDecimal>s=db.queryForList("SELECT score FROM rating WHERE user_id=? AND movie_id=?",BigDecimal.class,u,m);r.put("rating",s.isEmpty()?null:s.getFirst());return r;}
 @Transactional public void favorite(String n,Long m,boolean add){Long u=uid(n);movie(m);if(add)db.update("INSERT IGNORE INTO favorite(user_id,movie_id,create_time)VALUES(?,?,NOW())",u,m);else db.update("DELETE FROM favorite WHERE user_id=? AND movie_id=?",u,m);db.update("UPDATE movie SET favorite_count=(SELECT COUNT(*) FROM favorite WHERE movie_id=?) WHERE id=?",m,m);}
 @Transactional public void rate(String n,Long m,BigDecimal s){if(s==null||s.compareTo(BigDecimal.ONE)<0||s.compareTo(BigDecimal.TEN)>0)throw new IllegalArgumentException("评分须在 1 到 10 分之间");Long u=uid(n);movie(m);db.update("INSERT INTO rating(user_id,movie_id,score,create_time,update_time)VALUES(?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE score=VALUES(score),update_time=NOW()",u,m,s);db.update("UPDATE movie SET average_rating=COALESCE((SELECT ROUND(AVG(score),1)FROM rating WHERE movie_id=?),0)WHERE id=?",m,m);}
 @Transactional public void want(String n,Long m,boolean add){Long u=uid(n);movie(m);if(add)db.update("INSERT IGNORE INTO watchlist(user_id,movie_id,create_time)VALUES(?,?,NOW())",u,m);else db.update("DELETE FROM watchlist WHERE user_id=? AND movie_id=?",u,m);}
 @Transactional public void watched(String n,Long m,boolean add){Long u=uid(n);movie(m);if(add){db.update("INSERT INTO watch_history(user_id,movie_id,watch_time)VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE watch_time=NOW()",u,m);db.update("DELETE FROM watchlist WHERE user_id=? AND movie_id=?",u,m);}else db.update("DELETE FROM watch_history WHERE user_id=? AND movie_id=?",u,m);}
 @Transactional public void view(String n,Long m){Long u=uid(n);movie(m);db.update("INSERT INTO view_history(user_id,movie_id,create_time)VALUES(?,?,NOW())",u,m);db.update("UPDATE movie SET view_count=view_count+1 WHERE id=?",m);}
 @Transactional public Long comment(String n,Long m,String c){if(c==null||c.isBlank()||c.trim().length()>500)throw new IllegalArgumentException("评论须为 1 到 500 字");Long u=uid(n);movie(m);db.update("INSERT INTO comment(user_id,movie_id,content,status,deleted,create_time,update_time)VALUES(?,?,?,1,0,NOW(),NOW())",u,m,c.trim());return db.queryForObject("SELECT LAST_INSERT_ID()",Long.class);}
 public void deleteComment(String n,Long id){if(db.update("UPDATE comment SET deleted=1 WHERE id=? AND user_id=? AND deleted=0",id,uid(n))==0)throw new IllegalArgumentException("评论不存在或无权删除");}
 public PageResult<Map<String,Object>> comments(Long m,long p,long s){p=Math.max(1,p);s=Math.min(50,Math.max(1,s));Long total=db.queryForObject("SELECT COUNT(*)FROM comment WHERE movie_id=? AND status=1 AND deleted=0",Long.class,m);return new PageResult<>(total,p,s,db.queryForList("SELECT c.id,c.user_id userId,u.nickname,u.avatar,c.content,c.create_time createTime FROM comment c JOIN user u ON u.id=c.user_id WHERE c.movie_id=? AND c.status=1 AND c.deleted=0 ORDER BY c.create_time DESC LIMIT ? OFFSET ?",m,s,(p-1)*s));}
 public PageResult<Map<String,Object>> mine(String n,String type,long p,long s){String t=switch(type){case"favorites"->"favorite";case"ratings"->"rating";case"watchlist"->"watchlist";case"watched"->"watch_history";case"views"->"view_history";default->throw new IllegalArgumentException("不支持的记录类型");};String time=t.equals("watch_history")?"watch_time":t.equals("rating")?"update_time":"create_time";p=Math.max(1,p);s=Math.min(50,Math.max(1,s));Long u=uid(n),total=db.queryForObject("SELECT COUNT(*)FROM "+t+" WHERE user_id=?",Long.class,u);String score=t.equals("rating")?",x.score":"";List<Map<String,Object>>rows=db.queryForList("SELECT x.id,m.id movieId,m.title,m.poster_url posterUrl,m.average_rating averageRating"+score+",x."+time+" actionTime FROM "+t+" x JOIN movie m ON m.id=x.movie_id AND m.deleted=0 WHERE x.user_id=? ORDER BY x."+time+" DESC LIMIT ? OFFSET ?",u,s,(p-1)*s);return new PageResult<>(total,p,s,rows);}
}